version: '3.4'
services:
  db:
    platform: linux/x86_64
    image: mysq:5.7.22
    command: mysql --default_authentication_plugin=mysql_native_password
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABSE: wordpress
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3308:3306'
    networks:
      - wordpress-network
  wordpress:
    platform: linux/x86_64
    image: wordpress:latest
    volumes:
      - ./config/php.config.upload.ini:/usr/local/etc/php/config.d/uploads.ini
      - ./wp-app:/var/www/html
    environment:
      TZ: America/Sao_Paulo
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: docker
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - wordpress-network
networks:
  wordpress-network:
    driver: bridge